# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/03ab91d2-fe65-4609-82c9-cc145b31d8ff";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2CAE-80E1";
      fsType = "vfat";
    };

  fileSystems."/media/hdd" =
    { device = "/dev/disk/by-uuid/5C8C8D8D8C8D61FE";
      fsType = "ntfs";
      options = [ "uid=1000" "gid=100" "dmask=007" "fmask=117" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f15c9db6-5a2e-4126-84a8-d31296e77e0e"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
